import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  vi: {
    topBar: 'Giao & Nhận Hàng Miễn Phí Trên Toàn Sài Gòn',
    header: {
      aboutUs: 'Về Chúng Tôi',
      aboutJims: "Về TLaundry",
      ourTeam: 'Đội Ngũ Của Chúng Tôi',
      becomeFranchisee: 'Trở Thành Đối Tác Nhượng Quyền',
      services: 'Dịch Vụ',
      domestic: 'Giặt Ủi Gia Đình',
      commercial: 'Giặt Ủi Thương Mại',
      ironing: 'Dịch Vụ Là/Ủi Quần Áo',
      dryCleaning: 'Giặt Khô / Giặt Hấp',
      ndis: 'Dịch Vụ Hỗ Trợ NDIS',
      sports: 'Giặt Ủi Câu Lạc Bộ Thể Thao',
      linen: 'Giặt Chăn Ga Gối Đệm & Khăn',
      hcp: 'Dịch Vụ Hỗ Trợ HCP',
      careFacilities: 'Giặt Ủi Bệnh Viện & Cơ Sở Chăm Sóc',
      pricing: 'Bảng Giá',
      giftCard: 'Thẻ Quà Tặng',
      contact: 'Liên Hệ',
      requestQuote: 'Yêu Cầu Báo Giá Miễn Phí',
      phone: '131 546',
    },
    hero: {
      title1: 'Dịch Vụ Giặt Ủi',
      title2: 'Di Động Cá Nhân Hóa,',
      title3: 'Uy Tín & Chuyên Nghiệp.',
      subtitle: 'Chúng tôi Nhận & Giao hàng tận nơi trong vòng 24 giờ - tươi mới, sạch sẽ & tiện lợi — đúng lúc bạn cần!',
      btnQuote: 'Yêu Cầu Báo Giá Miễn Phí',
    },
    trustBar: [
      'Giao & Nhận Miễn Phí',
      'Báo Giá Miễn Phí Trong 2 Giờ',
      'Phục Vụ Toàn Sài Gòn',
      'Gia Đình & Thương Mại',
      "Cam Kết Chất Lượng TLaundry",
      'Nước Giặt 100% Thân Thiện Môi Trường',
    ],
    reviews: {
      title: "Xem Khách Hàng Nói Gì Về Dịch Vụ Giặt Ủi Của TLaundry",
      btnQuote: 'Yêu Cầu Báo Giá Miễn Phí Ngay Hôm Nay',
    },
    whoWeAre: {
      badge: "Về TLaundry",
      title: 'Dịch Vụ Giặt Ủi Di Động Nhận & Giao Tận Nơi Được Tin Tưởng Nhất tại Sài Gòn',
      desc1: "TLaundry đã và đang cách mạng hóa cách người dân Sài Gòn xử lý công việc giặt ủi. Chúng tôi kết hợp giặt sạch tiêu chuẩn chuyên nghiệp với sự tiện lợi tối đa khi giao nhận miễn phí tận nơi — tất cả trong 24 giờ.",
      desc2: 'Cho dù là quần áo gia đình hàng ngày, nhu cầu doanh nghiệp hay chăm sóc vải vóc đặc biệt, đội ngũ đối tác nhượng quyền được đào tạo của chúng tôi luôn mang lại chất lượng vượt trội đến tận cửa nhà bạn.',
      features: [
        'Giao & Nhận Miễn Phí Toàn Sài Gòn',
        'Dịch Vụ Giặt, Sấy & Gấp Gọn',
        'Sản Phẩm Thân Thiện Môi Trường',
        'Trả Hàng Nhanh Trong 24 Giờ',
      ],
      btnLearn: 'Tìm Hiểu Thêm Về Chúng Tôi',
    },
    promoCards: [
      {
        num: '01.',
        title: 'Yêu Cầu Báo Giá Miễn Phí',
        desc: 'Chỉ cần gọi cho đội ngũ của chúng tôi hoặc Yêu Cầu Báo Giá Miễn Phí trực tuyến & cho chúng tôi biết nhu cầu của bạn, bạn sẽ nhận được báo giá chỉ trong vài phút!',
        btn: 'Yêu cầu báo giá',
        href: '/booking',
      },
      {
        num: '02.',
        title: 'Liên Hệ Với Chúng Tôi',
        desc: 'Nếu bạn có bất kỳ câu hỏi nào khác về dịch vụ giặt ủi giao nhận tận nơi của chúng tôi, đừng ngần ngại liên hệ ngay hôm nay!',
        btn: 'Liên Hệ Ngay',
        href: '/contact',
      },
    ],
    servicesSection: {
      title: 'Dịch Vụ Giặt Ủi & Giặt Khô Tốt Nhất Dành Cho Khách Hàng',
      desc: 'Chúng tôi cung cấp đầy đủ các dịch vụ giặt ủi nhận tận nơi giúp cuộc sống của bạn trở nên dễ dàng hơn. Dù là quần áo gia đình hay nhu cầu thương mại, dịch vụ của chúng tôi luôn đảm bảo chất lượng vượt trội.',
      badge: 'Dịch Vụ Giặt Ủi Di Động',
    },
    howToBook: {
      title1: 'Cách Thức ',
      title2: 'Đặt Dịch Vụ',
      desc: "Đặt dịch vụ với TLaundry vô cùng nhanh chóng, dễ dàng và thuận tiện! Chỉ cần làm theo các bước đơn giản dưới đây.",
      btn: "Đặt Dịch Vụ Giặt Ủi TLaundry",
      steps: [
        { step: 1, title: 'Yêu cầu báo giá miễn phí' },
        { step: 2, title: 'Hẹn giờ lấy hàng' },
        { step: 3, title: 'Chúng tôi đến lấy đồ giặt' },
        { step: 4, title: 'Nhận quần áo sạch sẽ, gấp gọn mà không tốn sức' },
      ],
    },
    whyChooseUs: {
      title1: 'Tại Sao ',
      title2: 'Chọn Chúng Tôi?',
      items: [
        'Báo Giá Cung Cấp Trong 2 Giờ!',
        'Trung Tâm Hỗ Trợ tại Sài Gòn',
        "Tất Cả Dịch Vụ Được Bảo Hành Bởi TLaundry",
        'Nước Giặt Sản Xuất tại Sài Gòn & Thân Thiện Môi Trường',
        'Giao & Nhận Miễn Phí',
        'Bảo Hiểm Đầy Đủ',
        'Tất Cả Khai Thác Viên Đã Qua Kiểm Tra Lý Lịch',
        'Không Hợp Đồng Ràng Buộc',
      ],
    },
    socialTestimonials: {
      badge: 'Đánh Giá',
      title: 'Đánh Giá Từ Khách Hàng',
      desc: "Tại TLaundry, chúng tôi đã hoàn thành hàng ngàn lượt giặt cho khách hàng hài lòng từ hộ gia đình đến doanh nghiệp. Hãy nghe cảm nhận từ khách hàng của chúng tôi!",
      btn: 'Xem Thêm Đánh Giá',
    },
    instagram: {
      title: 'Theo Dõi Chúng Tôi Trên Instagram',
      btnLoadMore: 'Tải Thêm',
      btnFollow: '📸 Theo Dõi Trên Instagram',
    },
    partnerships: {
      title1: 'Đối Tác Đồng Hành ',
      title2: 'Cùng Chúng Tôi',
      subtext: 'Những Đối Tác Tự Hào Của Chúng Tôi!',
    },
    franchiseSection: {
      badge: 'Cơ Hội Nhượng Quyền',
      title: 'Bắt Đầu Kinh Doanh Giặt Ủi Jim\'s Của Riêng Bạn Ngay Hôm Nay!',
      desc: "Gia nhập TLaundry Group — Mạng lưới nhượng quyền thương hiệu được nhận diện hàng đầu tại Sài Gòn. Với quy trình đào tạo toàn diện và hệ thống đã được kiểm chứng, bạn hoàn toàn có thể tự vận hành doanh nghiệp thành công.",
      perks: [
        'Chi phí bắt đầu thấp & được đào tạo bài bản',
        'Khu vực độc quyền tại địa phương của bạn',
        'Làm chủ công việc với hệ thống uy tín từ Jim\'s',
        'Tham gia mạng lưới nhượng quyền số 1 tại Sài Gòn',
        'Hỗ trợ marketing và vận hành liên tục',
      ],
      btn: 'Tìm Hiểu Thêm Về Nhượng Quyền',
      quote: '"Gia nhập Jim\'s Laundry là quyết định tuyệt vời nhất của tôi. Tôi tự làm chủ, thời gian linh hoạt và thu nhập rất tốt. Sự hỗ trợ từ hệ thống thật tuyệt vời!"',
      name: '— Mark S., Đối tác nhượng quyền Queensland',
      highlights: [
        { strong: '500+', span: 'Đối Tác Nhượng Quyền' },
        { strong: '24 Giờ', span: 'Thời Gian Trả Hàng Trung Bình' },
        { strong: '100%', span: 'Mức Độ Hài Lòng' },
      ],
    },
    news: {
      title: 'Tin Tức Mới Nhất & Mẹo Giặt Ủi',
      readMore: 'Đọc Thêm →',
    },
    footer: {
      findUs: 'Theo dõi chúng tôi trên!',
      quickLinks: 'Liên Kết Nhanh',
      services: 'Dịch Vụ',
      laundryStates: 'Khu Vực Phục Vụ',
      newsletterTitle: 'Đồ Giặt Chất Đống? Nhận Ngay Ưu Đãi $10!',
      newsletterDesc: 'ĐĂNG KÝ ĐỂ NHẬN NGAY $10 CHO LẦN GIẶT ĐẦU TIÊN VÀ CÁC MẸO GIẶT ỦI HỮU ÍCH!',
      emailPlaceholder: 'Nhập địa chỉ email*',
      btnSubscribe: 'ĐĂNG KÝ',
      contactUs: 'Liên Hệ',
      copyright: "Bản quyền © 2026 TLaundry | Chính Sách Bảo Mật | Điều Khoản & Điều Kiện",
    },
    bookingPage: {
      heroTitle: 'Yêu Cầu Báo Giá Miễn Phí',
      heroSubtitle: 'Chúng tôi sẽ phản hồi trong vòng 2 giờ với báo giá cá nhân hóa!',
      step1: 'Loại Dịch Vụ',
      step2: 'Thông Tin Của Bạn',
      step3: 'Xác Nhận',
      selectServiceTitle: 'Bạn cần dịch vụ giặt ủi nào?',
      selectServiceSubtitle: 'Vui lòng chọn dịch vụ giặt ủi phù hợp nhất với nhu cầu của bạn.',
      detailsTitle: 'Thông Tin Cá Nhân & Giao Nhận',
      detailsSubtitle: 'Vui lòng cung cấp thông tin liên hệ và thời gian nhận hàng.',
      firstName: 'Tên',
      lastName: 'Họ',
      email: 'Địa chỉ Email',
      phone: 'Số điện thoại',
      address: 'Địa chỉ nhà (Số nhà & Tên đường)',
      suburb: 'Quận / Huyện (Suburb)',
      state: 'Bang / Tỉnh thành',
      pickupDate: 'Ngày nhận hàng mong muốn',
      pickupTime: 'Khung giờ nhận hàng',
      frequency: 'Tần suất dịch vụ',
      notes: 'Ghi chú thêm',
      btnContinue: 'Tiếp Tục →',
      btnBack: '← Quay Lại',
      btnReview: 'Xem Lại Yêu Cầu →',
      btnSubmit: 'Gửi Yêu Cầu Báo Giá ✓',
      confirmTitle: 'Xác Nhận Yêu Cầu Của Bạn',
      confirmSubtitle: 'Vui lòng kiểm tra kỹ thông tin trước khi gửi.',
      successTitle: 'Yêu Cầu Báo Giá Đã Được Gửi!',
      successDesc: 'Cảm ơn bạn đã liên hệ! Đội ngũ của chúng tôi tại Sài Gòn sẽ liên hệ lại với bạn trong vòng 2 giờ kèm báo giá chi tiết.',
      btnSubmitAnother: 'Gửi Yêu Cầu Khác',
      btnBackHome: 'Về Trang Chủ',
    },
    pricingPage: {
      heroTitle: 'Bảng Giá Dịch Vụ Giặt Ủi',
      heroSubtitle: 'Giá cả minh bạch, không chi phí ẩn. Nhận báo giá miễn phí trong 2 giờ!',
      title: 'Mức Giá Minh Bạch & Hợp Lý',
      subtitle: 'Tất cả chi phí được tính dựa trên nhu cầu thực tế của bạn. Đội ngũ tại Sài Gòn sẽ gửi báo giá cá nhân hóa trong 2 giờ.',
      additionalTitle: 'Bảng Giá Tham Khảo Theo Món',
      additionalSubtitle: 'Mức giá tham khảo — báo giá chính xác sẽ được xác nhận sau khi kiểm tra.',
      inclusionsTitle: 'Tất Cả Dịch Vụ Đều Bao Gồm',
      inclusions: [
        { icon: '🚚', text: 'Giao & Nhận Miễn Phí' },
        { icon: '🌿', text: 'Nước Giặt Thân Thiện Môi Trường' },
        { icon: '⚡', text: 'Trả Hàng Trong 24 Giờ' },
        { icon: '🏅', text: "Cam Kết Chất Lượng TLaundry" },
      ],
    },
    servicesPage: {
      heroTitle: 'Dịch Vụ Giặt Ủi Của Chúng Tôi',
      heroSubtitle: 'Dịch vụ giặt ủi nhận tận nơi toàn diện trên Toàn Sài Gòn — từ giặt quần áo gia đình đến dịch vụ thương mại chuyên nghiệp.',
      ctaTitle: 'Sẵn Sàng Trải Nghiệm Sự Khác Biệt Từ Jim\'s?',
      ctaSubtitle: 'Nhận báo giá miễn phí trong 2 giờ. Giao nhận tận nơi miễn phí toàn Sài Gòn!',
    },
    contactPage: {
      heroTitle: 'Liên Hệ Với Chúng Tôi',
      heroSubtitle: 'Bạn có thắc mắc? Đội ngũ hỗ trợ tại Sài Gòn luôn sẵn sàng giúp đỡ bạn trong vòng 2 giờ!',
      infoTitle: 'Thông Tin Liên Hệ',
      infoDesc: 'Dù bạn muốn hỏi về dịch vụ, bảng giá hay đặt lịch lấy hàng, đội ngũ thân thiện của chúng tôi luôn sẵn sàng hỗ trợ 7 ngày trong tuần!',
      formTitle: 'Gửi Tin Nhắn Cho Chúng Tôi',
      fullName: 'Họ và tên',
      subject: 'Chủ đề',
      message: 'Nội dung tin nhắn',
      btnSend: 'Gửi Tin Nhắn →',
      successTitle: 'Tin Nhắn Đã Được Gửi!',
      successDesc: 'Cảm ơn bạn đã liên hệ. Chúng tôi sẽ phản hồi bạn trong vòng 2 giờ.',
      faqTitle: 'Các Câu Hỏi Thường Gặp',
    },
    franchisePage: {
      heroTitle: 'Nhượng Quyền Giặt Ủi Jim\'s Services',
      heroSubtitle: 'Làm chủ công việc kinh doanh của chính bạn. Gia nhập mạng lưới nhượng quyền số 1 tại Sài Gòn.',
      ctaEnquire: 'Đăng Ký Tư Vấn Ngay',
      whyTitle: 'Tại Sao Chọn Nhượng Quyền Jim\'s Laundry?',
      howTitle: 'Quy Trình Bắt Đầu',
      testimonialTitle: 'Chia Sẻ Từ Các Đối Tác Nhượng Quyền',
      btnApply: 'Đăng Ký Trở Thành Đối Tác Ngay Hôm Nay',
    },
    giftCardPage: {
      heroTitle: 'Thẻ Quà Tặng Jim\'s Laundry',
      heroSubtitle: 'Món quà thiết thực mang lại quần áo sạch sẽ, thơm tho! Phù hợp cho mọi dịp.',
      selectAmount: 'Chọn Mệnh Giá',
      customAmount: 'Hoặc Nhập Số Tiền Tùy Chỉnh ($)',
      inclusionsTitle: 'Quyền Lợi Thẻ Quà Tặng',
      detailsTitle: 'Thông Tin Thẻ Quà Tặng',
      recipientDetails: 'THÔNG TIN NGƯỜI NHẬN',
      senderDetails: 'THÔNG TIN NGƯỜI GỬI',
      recipientName: 'Tên người nhận',
      recipientEmail: 'Email người nhận',
      senderName: 'Tên người gửi',
      senderEmail: 'Email người gửi',
      messageLabel: 'Lời chúc cá nhân (không bắt buộc)',
      deliveryDate: 'Ngày gửi thẻ',
      btnPurchase: '🎁 Mua Thẻ Quà Tặng Ngay',
      orderedTitle: 'Đã Đặt Thẻ Quà Tặng Thành Công!',
      orderedDesc: 'Thẻ quà tặng Jim\'s Laundry sẽ được gửi đến email người nhận đúng ngày bạn đã chọn.',
    },
  },
  en: {
    topBar: 'FREE Pick-Up & Delivery Sài Gòn',
    header: {
      aboutUs: 'About Us',
      aboutJims: "About TLaundry",
      ourTeam: 'Our Team',
      becomeFranchisee: 'Become A Franchisee',
      services: 'Services',
      domestic: 'Domestic Laundry',
      commercial: 'Commercial Laundry',
      ironing: 'Ironing Services',
      dryCleaning: 'Dry Cleaning',
      ndis: 'NDIS Support Services',
      sports: 'Sporting Clubs Laundry',
      linen: 'Linen, Bedding & Bath',
      hcp: 'HCP Support Services',
      careFacilities: 'Care Facilities Laundry',
      pricing: 'Pricing List',
      giftCard: 'Gift Card',
      contact: 'Contact Us',
      requestQuote: 'Request A Free Quote',
      phone: '131 546',
    },
    hero: {
      title1: 'Personalised',
      title2: 'Mobile Laundry Service,',
      title3: 'Professionally Trusted.',
      subtitle: 'We Pick-up & Deliver all within 24 hours - fresh, clean & convenient — exactly when you need!',
      btnQuote: 'Request A Free Quote',
    },
    trustBar: [
      'Free Pick-up & Delivery',
      'Get a FREE Quote within 2 hours',
      'Servicing Sài Gòn',
      'Domestic & Commercial',
      "TLaundry Work Guarantee",
      '100% Eco-Friendly Detergents',
    ],
    reviews: {
      title: "See What Our Customers Are Saying About TLaundry",
      btnQuote: 'Request A Free Quote Today',
    },
    whoWeAre: {
      badge: "About TLaundry",
      title: "Sài Gòn's Most Trusted Mobile Laundry Pick-Up & Delivery Service",
      desc1: "TLaundry has been revolutionising the way Sài Gònns handle their laundry. We combine professional-grade cleaning with the ultimate convenience of free pick-up and delivery — all within 24 hours.",
      desc2: 'Whether it\'s everyday household laundry, commercial needs, or specialised care for delicate fabrics, our trained franchisees deliver exceptional quality right to your door.',
      features: [
        'Free Pick-up & Delivery Sài Gòn',
        'Wash, Dry & Fold Service',
        'Eco-Friendly Products',
        '24-Hour Turnaround',
      ],
      btnLearn: 'Learn More About Us',
    },
    promoCards: [
      {
        num: '01.',
        title: 'Request A Free Quote',
        desc: "Simply call our team or Request A Free Quote online & let them know what you need, and you'll receive a quote in minutes!",
        btn: 'Request a quote',
        href: '/booking',
      },
      {
        num: '02.',
        title: 'Get in Touch',
        desc: "If you have any other questions about our laundry pick-up & delivery services, feel free to contact us today! We've got your back.",
        btn: 'Contact Us',
        href: '/contact',
      },
    ],
    servicesSection: {
      title: 'The Best Laundry and Dry Cleaning Service Provided to Our Customers',
      desc: 'We offer a comprehensive range of pick-up laundry services designed to make your life easier. Whether it\'s everyday household laundry, commercial needs, or specialised care, our services are tailored to deliver exceptional quality and convenience.',
      badge: 'Mobile Laundry Service',
    },
    howToBook: {
      title1: 'How to ',
      title2: 'Book',
      desc: "Booking with TLaundry is quick, easy, and hassle-free! Just follow the simple steps below to schedule your service and let us take care of the rest.",
      btn: "Book TLaundry",
      steps: [
        { step: 1, title: 'Request a free quote' },
        { step: 2, title: 'Book in a pick up time' },
        { step: 3, title: 'Have your laundry collected' },
        { step: 4, title: 'Enjoy your wash & folded laundry without the stress' },
      ],
    },
    whyChooseUs: {
      title1: 'Why ',
      title2: 'Choose Us?',
      items: [
        'All Quoted Provided within 2 Hours!',
        'Sài Gònn Based Call Centre',
        "All Services backed by the TLaundry Work Guarantee",
        'Sài Gònn-Made & Environmentally Free Detergents',
        'Free Pick-up & Delivery',
        'Fully Insured',
        'All Franchisees Police Checked',
        'No Lock-in Contract',
      ],
    },
    socialTestimonials: {
      badge: 'Testimonials',
      title: 'Customer Testimonials',
      desc: "At TLaundry, we've completed thousands of washes for satisfied customers across households and businesses alike. Hear from our Happy Customers about their experiences with us!",
      btn: 'Read More Reviews',
    },
    instagram: {
      title: 'Follow Us on Instagram',
      btnLoadMore: 'Load More',
      btnFollow: '📸 Follow on Instagram',
    },
    partnerships: {
      title1: 'See Whose Dirty Laundry ',
      title2: 'Has Been Aired?',
      subtext: 'Our Proud Partnerships!',
    },
    franchiseSection: {
      badge: 'Become a Franchisee',
      title: 'Start Your Own Jim\'s Laundry Business Today!',
      desc: "Join the TLaundry Group — Sài Gòn's most recognised franchise network. With full training, ongoing support and a proven system, you can run your own successful laundry business.",
      perks: [
        'Low start-up costs with full training provided',
        'Exclusive territory in your local area',
        'Be your own boss with Jim\'s proven system',
        'Join Sài Gòn\'s #1 franchise network',
        'Ongoing marketing and business support',
      ],
      btn: 'Learn More About Franchising',
      quote: '"Joining Jim\'s Laundry has been the best decision I\'ve ever made. I\'m my own boss, working flexible hours and earning great income. The support from the network is outstanding!"',
      name: '— Mark S., Jim\'s Laundry Franchisee, Queensland',
      highlights: [
        { strong: '500+', span: 'Franchisees Nationwide' },
        { strong: '24hrs', span: 'Average Turnaround' },
        { strong: '100%', span: 'Satisfaction Rate' },
      ],
    },
    news: {
      title: 'Latest News & Laundry Tips',
      readMore: 'Read More →',
    },
    footer: {
      findUs: 'Find us on!',
      quickLinks: 'Quick Links',
      services: 'Services',
      laundryStates: 'Laundry Locations',
      newsletterTitle: 'Laundry Piling Up? Get $10 Off!',
      newsletterDesc: 'SIGN UP TO RECEIVE $10 OFF YOUR FIRST LAUNDRY SERVICE & DIY TIPS & TRICKS!',
      emailPlaceholder: 'Email Address*',
      btnSubscribe: 'SUBSCRIBE',
      contactUs: 'Contact Us',
      copyright: "Copyright © 2026 TLaundry | Privacy Policy | Terms and Conditions",
    },
    bookingPage: {
      heroTitle: 'Request A Free Quote',
      heroSubtitle: 'We\'ll get back to you within 2 hours with a personalised quote!',
      step1: 'Service Type',
      step2: 'Your Details',
      step3: 'Confirmation',
      selectServiceTitle: 'What service do you need?',
      selectServiceSubtitle: 'Select the laundry service that best suits your needs.',
      detailsTitle: 'Your Details',
      detailsSubtitle: 'Please provide your contact and pickup information.',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email Address',
      phone: 'Phone Number',
      address: 'Street Address',
      suburb: 'Suburb',
      state: 'State',
      pickupDate: 'Preferred Pickup Date',
      pickupTime: 'Preferred Pickup Time',
      frequency: 'Service Frequency',
      notes: 'Additional Notes',
      btnContinue: 'Continue →',
      btnBack: '← Back',
      btnReview: 'Review Quote →',
      btnSubmit: 'Submit Quote Request ✓',
      confirmTitle: 'Confirm Your Request',
      confirmSubtitle: 'Please review your details before submitting.',
      successTitle: 'Quote Request Submitted!',
      successDesc: 'Thank you for reaching out! Our Sài Gònn-based team will contact you within 2 hours with a personalised quote.',
      btnSubmitAnother: 'Submit Another',
      btnBackHome: 'Back to Home',
    },
    pricingPage: {
      heroTitle: 'Laundry Pricing List',
      heroSubtitle: 'Transparent, affordable pricing with no hidden fees. Get a free quote within 2 hours!',
      title: 'Simple, Transparent Pricing',
      subtitle: 'All pricing is based on your specific requirements. Request a free quote and our Sài Gònn-based team will provide a personalised price within 2 hours.',
      additionalTitle: 'Additional Item Pricing',
      additionalSubtitle: 'Indicative pricing — final quotes provided after assessment.',
      inclusionsTitle: 'All Services Include',
      inclusions: [
        { icon: '🚚', text: 'Free Pick-up & Delivery' },
        { icon: '🌿', text: 'Eco-Friendly Detergents' },
        { icon: '⚡', text: '24-Hour Turnaround' },
        { icon: '🏅', text: "TLaundry Work Guarantee" },
      ],
    },
    servicesPage: {
      heroTitle: 'Our Laundry Services',
      heroSubtitle: 'Comprehensive pick-up laundry services across Sài Gòn — from everyday household washing to specialist commercial and care facility laundry.',
      ctaTitle: 'Ready to Experience the Jim\'s Difference?',
      ctaSubtitle: 'Get a free quote within 2 hours. Free pick-up & delivery Sài Gòn!',
    },
    contactPage: {
      heroTitle: 'Contact Us',
      heroSubtitle: 'Have a question? Our Sài Gònn-based team is ready to help you. We respond within 2 hours!',
      infoTitle: 'Get In Touch',
      infoDesc: 'Whether you have questions about our services, pricing or would like to book a pick-up, our friendly team is here to help 7 days a week!',
      formTitle: 'Send Us a Message',
      fullName: 'Full Name',
      subject: 'Subject',
      message: 'Message',
      btnSend: 'Send Message →',
      successTitle: 'Message Sent!',
      successDesc: 'Thank you for reaching out! Our team will get back to you within 2 hours.',
      faqTitle: 'Frequently Asked Questions',
    },
    franchisePage: {
      heroTitle: 'Become A Jim\'s Laundry Franchisee',
      heroSubtitle: 'Be your own boss. Join Sài Gòn\'s #1 franchise network and build a thriving laundry business.',
      ctaEnquire: 'Enquire Now',
      whyTitle: 'Why Choose Jim\'s Laundry Franchise?',
      howTitle: 'How to Get Started',
      testimonialTitle: 'What Our Franchisees Say',
      btnApply: 'Apply to Become a Franchisee Today',
    },
    giftCardPage: {
      heroTitle: 'Jim\'s Laundry Gift Cards',
      heroSubtitle: 'Give the gift of fresh, clean laundry! Perfect for any occasion.',
      selectAmount: 'Select Amount',
      customAmount: 'Custom Amount ($)',
      inclusionsTitle: 'Gift Card Inclusions',
      detailsTitle: 'Gift Card Details',
      recipientDetails: 'RECIPIENT DETAILS',
      senderDetails: 'YOUR DETAILS',
      recipientName: 'Recipient Name',
      recipientEmail: 'Recipient Email',
      senderName: 'Your Name',
      senderEmail: 'Your Email',
      messageLabel: 'Personal Message (optional)',
      deliveryDate: 'Delivery Date',
      btnPurchase: '🎁 Purchase Gift Card',
      orderedTitle: 'Gift Card Ordered!',
      orderedDesc: 'Your gift card will be sent to the recipient on the selected date.',
    },
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('vi'); // Default to Vietnamese

  const toggleLanguage = () => {
    setLang(prev => (prev === 'vi' ? 'en' : 'vi'));
  };

  const t = translations[lang] || translations.vi;

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);


